import { db } from './firebase-config.js';
import { collection, addDoc, getDocs, query, orderBy, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const students=[['Ahmet Kaya','1233'],['Samet Balcı','155'],['Elif Yılmaz','2041'],['Mert Demir','3120'],['Zeynep Şahin','418'],['Ece Aydın','927'],['Can Arslan','1440'],['Deniz Koç','203'],['Berk Çetin','1875'],['Duru Özkan','511'],['Kerem Kaya','1612'],['Ada Kılıç','744']].map(([name,number])=>({name,number}));
const views=['welcomeView','teacherView','adminView'];
function show(id){views.forEach(v=>$(v).classList.toggle('active',v===id));}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2500)}
function setup(){ $('sectionSelect').innerHTML='<option value="">Şube seç</option>'+[...'ABCDEFGHIJKLM'].map(x=>`<option value="${x}">${x} Şubesi</option>`).join(''); $('lessonSelect').innerHTML='<option value="">Ders seç</option>'+Array.from({length:7},(_,i)=>`<option value="${i+1}">${i+1}. Ders</option>`).join(''); }
async function teachers(){const s=await getDocs(collection(db,'teachers'));const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||'').localeCompare(b.name||'','tr'));$('teacherCount').textContent=`${rows.length} kayıt`;$('teacherList').innerHTML=rows.length?rows.map(t=>`<div class="simple-row"><div><strong>${esc(t.name)}</strong><small>Öğretmen</small></div></div>`).join(''):'<div class="empty">Henüz öğretmen yok.</div>';$('teacherSelect').innerHTML='<option value="">Öğretmen seç</option>'+rows.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');return rows;}
function render(){ $('studentList').innerHTML=students.map((s,i)=>`<div class="student-row"><div><strong>${esc(s.name)}</strong><small>Öğrenci No: ${esc(s.number)}</small></div><select class="attendance" data-i="${i}"><option value="present">🟢 Var</option><option value="absent">🔴 Yok</option></select></div>`).join('');document.querySelectorAll('.attendance').forEach(e=>e.addEventListener('change',()=>{e.classList.toggle('absent',e.value==='absent');summary()}));$('saveAttendance').disabled=false;summary();}
function summary(){const a=[...document.querySelectorAll('.attendance')];$('summary').textContent=`${a.length} öğrenci • ${a.filter(x=>x.value==='absent').length} yok`;}
async function absences(){try{const q=query(collection(db,'attendance'),orderBy('createdAt','desc'),limit(50));const s=await getDocs(q);const a=s.docs.map(d=>d.data()).filter(x=>x.status==='absent');$('absenceList').innerHTML=a.length?a.map(x=>`<div class="simple-row"><div><strong>${esc(x.studentName)}</strong><small>${esc(x.teacherName)} • ${x.class}. Sınıf ${esc(x.section)} • ${x.lesson}. Ders</small></div><span class="pill">🔴 Yok</span></div>`).join(''):'<div class="empty">Henüz devamsızlık kaydı yok.</div>';}catch(e){$('absenceList').innerHTML='<div class="empty">Kayıtlar okunamadı. Firestore Rules kontrol edilmeli.</div>';}}
$('teacherEntry').onclick=async()=>{show('teacherView');try{await teachers()}catch(e){toast('Öğretmenler okunamadı. Firestore bağlantısını kontrol et.')}};
$('adminEntry').onclick=async()=>{show('adminView');try{await teachers();await absences()}catch(e){toast('Firestore bağlantısı kontrol edilmeli.')}};
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('welcomeView'));
$('loadStudents').onclick=()=>{if(!$('teacherSelect').value||!$('classSelect').value||!$('sectionSelect').value||!$('lessonSelect').value)return toast('Önce tüm seçimleri yap.');$('teacherPanelTitle').textContent=$('teacherSelect').selectedOptions[0].textContent;render()};
$('saveAttendance').onclick=async()=>{const teacherId=$('teacherSelect').value,classNo=$('classSelect').value,section=$('sectionSelect').value,lesson=Number($('lessonSelect').value),teacherName=$('teacherSelect').selectedOptions[0].textContent;const a=[...document.querySelectorAll('.attendance')];try{for(let i=0;i<a.length;i++)await addDoc(collection(db,'attendance'),{studentName:students[i].name,studentNumber:students[i].number,status:a[i].value,teacherId,teacherName,class:classNo,section,lesson,createdAt:serverTimestamp()});toast('Yoklama kaydedildi.');summary()}catch(e){console.error(e);toast('Kayıt başarısız. Firestore Rules kontrol edilmeli.')}};
$('teacherForm').onsubmit=async e=>{e.preventDefault();const first=$('firstName').value.trim(),last=$('lastName').value.trim();if(!first||!last)return;try{await addDoc(collection(db,'teachers'),{name:`${first} ${last}`,firstName:first,lastName:last,createdAt:serverTimestamp()});e.target.reset();$('adminMessage').textContent='Öğretmen başarıyla eklendi.';await teachers();toast('Öğretmen eklendi.')}catch(err){console.error(err);$('adminMessage').textContent='Öğretmen eklenemedi. Firestore Rules kontrol edilmeli.'}};
setup();
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
